# Generated by Django 3.1.5 on 2021-02-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210202_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntary',
            options={'verbose_name_plural': 'Volunteers'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='scholarity',
            field=models.CharField(choices=[('ANF', 'Analfabeto'), ('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESC', 'Superior completo')], max_length=4),
        ),
    ]
