# Generated by Django 3.1.5 on 2021-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20210203_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('event_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Evento')),
                ('date_event', models.DateTimeField()),
                ('event_details', models.TextField()),
                ('materials', models.TextField()),
                ('volunteers', models.ManyToManyField(related_name='evento_set', to='users.Voluntary', verbose_name='volunteers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('cost', models.FloatField(verbose_name='R$0.00')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalhes do gasto')),
                ('event', models.ManyToManyField(related_name='cost_set', to='events.Event', verbose_name='event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('collection', models.FloatField(verbose_name='R$0.00')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalhes do gasto')),
                ('event', models.ManyToManyField(related_name='collection_set', to='events.Event', verbose_name='event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
