# Generated by Django 3.1.5 on 2021-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210203_1643'),
        ('events', '0002_auto_20210204_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_set', to='users.Voluntary', verbose_name='volunteers'),
        ),
    ]
