# Generated by Django 3.1.5 on 2021-02-04 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20210203_1643'),
        ('events', '0003_auto_20210204_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('donations.donation',),
        ),
    ]
