# Generated by Django 3.1.5 on 2021-02-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210203_1643'),
        ('events', '0004_eventdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='event',
        ),
        migrations.AddField(
            model_name='collection',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_set', to='events.event', verbose_name='event'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cost',
            name='event',
        ),
        migrations.AddField(
            model_name='cost',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_set', to='events.event', verbose_name='event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='Feijoada APREPI', max_length=150, verbose_name='Nome do Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(related_name='event_set', to='users.Voluntary', verbose_name='volunteers'),
        ),
    ]
