# Generated by Django 3.1.5 on 2021-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210203_1643'),
        ('events', '0005_auto_20210205_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='event_set', to='users.Voluntary', verbose_name='volunteers'),
        ),
    ]
