# Generated by Django 3.1.5 on 2021-01-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210115_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=32)),
                ('neighborhood', models.CharField(blank=True, max_length=32, null=True)),
                ('address_number', models.CharField(blank=True, max_length=8, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
