# Generated by Django 3.1.5 on 2021-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('in_process', 'Em processo'), ('pending', 'Pendente'), ('authorized', 'Autorizado'), ('rejected', 'Rejeitado'), ('charged_back', 'Estornado'), ('approved', 'Aprovado')], default='pending', max_length=12),
        ),
    ]
