# Generated by Django 3.1.5 on 2021-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20210129_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('in_process', 'Em processo'), ('pending', 'Pendente'), ('authorized', 'Autorizado'), ('rejected', 'Rejeitado'), ('charged_back', 'Estornado')], default='pending', max_length=12),
        ),
    ]
