# Generated by Django 3.1.5 on 2021-02-03 19:43

from django.db import migrations, models
import donations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20210202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=20, validators=[donations.validators.card_validator]),
        ),
    ]
